version: 0.1

log:
  level: info
  formatter: text

storage:
  delete:
    enabled: true

  gcs:
    bucket: replreg
    keyfile: /etc/gcs.json
    rootdirectory: /

http:
  addr: 0.0.0.0:__PORT__
  secret: __REPLREG_SECRET__
  host: __REPLREG_HOST__
  debug:
    addr: 0.0.0.0:5001
    prometheus:
      enabled: false

notifications:
  events:
    includereferences: true
  endpoints:
    - name: registry-hooks
      disabled: false
      url: __HOOK_URI__
      headers:
        Authorization: ["Token __HOOK_TOKEN__"]
      timeout: 1s
      threshold: 10
      backoff: 1s
